language: node_js
node_js:
  - 14.15.0
install:
  - npm install
script:
  - npm run test
on:
    repo: eduardou-ub/HelloWorld
    branches:    
      only:      
        - master
deploy:
  provider: heroku
  api_key:
    secure: oRgjVwRwJBAazTYmFEeoEut24Caw35v2tffZafMwMiWcU0RHwsAMFW3mCBTGm0GwZVonqUPClmb2lJgDMOjh9f2xLnfrNRrghHkJKXsElKrOb2KwGtP5miiY3l+1MeUm0ZqCJ629xcoXVJEcPKF9IRdi68WWqSzPDeKMTbkwttx6HShUUYH4f0eMYZc1Huw583C097Xg9juEg+ZMyW6f36m+Q7FP+lDNwIYNJDuSUrNnVWqqq1UETkMf48wmFpZr3tnLf5HiQLJTDCvVQ5MzmB+QkkQ6OUhKgAbuu67lBuxgXetyZ5Fy0sR+2TV8EZTkecenb0NOokJuvhoY9/Ovb4EaCwqzF5bAz9oElKEtSck03djAAFb5AwOA3mEZ0ATvXt/gn/FbNqjFtxBi2HMmbRP8NUY1mOMS0v/0hihOcKG+rakgrFZerG2eykwZxTRF2LX5hcDz27oq9rCMNwoA863Qu7T5EOgUro+envkS+szmYgL1zpmbYRtoHKrPC1eVwouD8HAMNwUkyHYgQdvRAw8EwGW0YfKMfFUgZHFWRtsoGxo7uNqSsMV1+00gziV9uVD9vEAdNcHdk+MmelW1Wfc1JmXp1QmOMmmN5xNcCLG+Eb5ymayK0oJchs4pFkOOWw2MwBjA0rJI/XmkH7S9z4skrKa8QmH7338kcRgiv9g=
  app:
    master: node-hello-world-1-production
