language: node_js
node_js:
- 14.15.0
install:
- npm install
script:
- npm run test
branches:
  only:
  - Develop
  - Master
deploy:
  provider: heroku
  api_key:
    secure: G2g1iSgk7/4Oal3+F+n2vcAqs9qDhu/Kfa5pqDA1v0U/Urc4HjnwMOK2X9vvDYDKej0LVaV+GvunYIrnP01IerhEsYtmSAh5wTO6VJPbQLFiUdCEblaMCVPDlk2UgezCv+jfkHwwF5a/ePkmn5f3efwrnQvaqrCLs5ewSqJkqJfhzRdqJG8C/NpT5Sl4rUd67JibCb3By8v0/VJ8VnpjWZ4oLNwqlLqS+ZXBLnLUFjvW6GeWzM/FeoQtaUGd4HWzkT3OqEoIgeB6t9Of6BXcwbBIdvS4/LmNKUpa5kJNdXDi+5bVBft0mIq4crQlcuQ4vwkZ33cw5Xfj89Pqj8l9V+5BKtQiSr2oKclie/WRxLUG1fOH2CrOJKsQTj6D8IWmxsInJ1BbOsISydzhu4M+3N6/KrLMILxkuccBvb2aUHoSuAIBv9MCTfN/IJrlWsS3Dut9fx7eEHn64A4kBKvgAGt7na6ca0qqJjmkk4YYcVsxBaUJHvUfyOBwa/r2lFBQGeGJXw8zTb6oaHlRgstZZU4zo1/B5oFXj48QlzEqKYUSquEzgedvbJ560+5g0dKDpr6XaaIOPJ92ybyyXN+DYqiisCrD2/gLmacgBhBVuVvxlXOOJAEfkayK+QL0d2NHCM7t7PNjte6HbNk0v0QJ+1rwaPiHH6GMeZdsffXPohc=
app:
  Develop: node-hello-world-1-staging
  Master: node-hello-world-1-production